FROM node:16-alpine
USER node
ENV NODE_ENV=production
WORKDIR /client
COPY --chown=node:node package.json package-lock.json ./
RUN npm ci --only=production
COPY --chown=node:node . .
EXPOSE 3000
CMD ["npm", "run", "start"]
