FROM node:16-alpine
USER node
ENV NODE_ENV=production
WORKDIR /paiement
COPY --chown=node:node package.json package-lock.json ./
RUN npm ci --only=production
COPY --chown=node:node . .
EXPOSE 8080
CMD ["node", "server.js"]
